name: Keep Running
run-name: ${{ gitea.actor }} is running spotify.local CI pipeline 🚀
on: [push]
concurrency: 'true'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Building project
        run: npm run build
      - name: Creating Linux Archive
        uses: vimtor/action-zip@v1.1
        with:
          files: out/kr-linux
          dest: linux.zip
      - name: Upload Linux Archive
        uses: actions/upload-artifact@v3
        with:
          path: linux.zip
      - name: Creating MacOS Archive
        uses: vimtor/action-zip@v1.1
        with:
          files: out/kr-macos
          dest: macos.zip
      - name: Upload MacOS Archive
        uses: actions/upload-artifact@v3
        with:
          path: macos.zip
      - name: Creating Windows Archive
        uses: vimtor/action-zip@v1.1
        with:
          files: out/kr-win.exe
          dest: windows.zip
      - name: Upload Windows Archive
        uses: actions/upload-artifact@v3
        with:
          path: windows.zip
